local dotfiles_home=~/.files

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source <(antibody init)

zstyle ':prezto:*:*' color 'yes'

antibody bundle << EOF
  jeffreytse/zsh-vi-mode

  sorin-ionescu/prezto
  sorin-ionescu/prezto path:modules/history
  sorin-ionescu/prezto path:modules/directory
  sorin-ionescu/prezto path:modules/utility

  zsh-users/zsh-history-substring-search
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  zdharma-continuum/fast-syntax-highlighting
  zdharma-continuum/history-search-multi-word
  MichaelAquilina/zsh-you-should-use
  laggardkernel/zsh-thefuck

  romkatv/powerlevel10k
EOF

source $dotfiles_home/modules/config.zsh
source $dotfiles_home/modules/alias.zsh
source $dotfiles_home/modules/ghop.zsh
source $dotfiles_home/p10k_config/p10k.zsh
